version: "3.9"
services:
  app:
    build: .
    container_name: wealth-mgr
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_SECRET=dev-secret
      - NEXTAUTH_URL=http://localhost:4000
      - PORT=4000
    command: pnpm dev
