import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "@/components/modules/layout/AppShell";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";

/** Geist 无衬线字体配置，用于主要界面文本 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/** Geist 等宽字体配置，用于代码与数字展示 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/** 应用级元数据配置，用于 SEO 与页面标题 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 根布局组件
 *
 * 作为 Next.js App Router 的顶层布局，负责：
 * - 注入全局字体变量
 * - 提供主题切换能力（ThemeProvider）
 * - 包裹应用外壳（AppShell，含导航与侧边栏）
 * - 挂载全局 Toast 通知
 *
 * @param children - 页面内容，由路由系统自动注入
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider disableTransitionOnChange>
          <AppShell>{children}</AppShell>
          <Toaster expand={false} position="top-center" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
